# Generated by Django 5.1.4 on 2025-02-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
