# Generated by Django 5.1.4 on 2025-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_image_url_news_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatars'),
        ),
    ]
